app/urls.py
from django.conf.urls import url

from app import views

app_name = 'app'

urlpatterns = [
    #auth
    url(r'^login/$', views.authenticate.auth_login, name='auth_login'),
    url(r'^logout/$', views.authenticate.auth_logout, name='auth_logout'),

    #ingredient views
    url(r'^ingredients/$', views.ingredient.list_ingredients, name="list_ingredients"),
    url(r'^ingredients/create/$', views.ingredient.create_ingredients, name="create_ingredients"),
    url(r'^ingredients/(?P<ingredient_id>[0-9]+)/delete/$',
        views.ingredient.delete_ingredients, name="delete_ingredients"),
    url(r'^ingredients/(?P<ingredient_id>[0-9]+)/edit/$',
        views.ingredient.edit_ingredient, name="edit_ingredient"),

    #recipe views
    url(r'^recipes/$', views.recipes.list_recipes, name="list_recipes"),
    url(r'^recipes/getJSON/$', views.recipes.get_recipes_as_json, name="list_recipes_json"),

    #users views
    url(r'^users/$', views.users.list_users, name="list_users"),
    url(r'^users/(?P<user_id>[0-9]+)/$',
        views.users.user_details, name="user_details"),

    #home view
    url(r'^$', views.home.home_get, name='home'),
]

idealfoods/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('app.urls')),
]

app/views/home.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_protect


@require_http_methods(["GET"])
def home_get(request):
    return render(request, 'app/home.html', {})

app/views/ingredient.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.decorators.http import require_http_methods
from django.http import JsonResponse, QueryDict
from django.template import loader
from django.db import IntegrityError
from django.db.models import ProtectedError

from app.models import Ingredient, Nutrient
from app.configs import ModalConfig, IconConfig, FormConfig
from app.forms import AddIngredientForm
from app.helper_functions import is_super_admin, is_admin
from app.builders.ingredients_builders import build_edit_ingredient_icon, \
    build_remove_ingredient_icon, build_cancel_ingredient_edit_icon, \
    build_confirm_ingredient_edit_icon, build_ingredients_table

def _get_edit_icon_html():
    edit_icon = build_edit_ingredient_icon()
    return loader.get_template('app/partials/_icon.html').\
        render({'config': edit_icon})

def _get_remove_icon_html():
    remove_icon = build_remove_ingredient_icon()
    return loader.get_template('app/partials/_icon.html').\
        render({'config': remove_icon})


@login_required
@require_http_methods(["GET"])
def list_ingredients(request):
    add_ingredients_form_config = FormConfig(
        form=AddIngredientForm()
    )

    add_ingredient_modal_config = ModalConfig(
        modal_id='addIngredientModal',
        modal_class='add-ingredient-modal',
        content=[add_ingredients_form_config],
        title='Add ingredient',
        form_class='add-ingredient-form'
    )

    ingredients_table_config = build_ingredients_table()

    return render(request, 'app/ingredients.html', {
        'add_ingredient_modal_config': add_ingredient_modal_config,
        'ingredients_table_config': ingredients_table_config,
    })

@user_passes_test(is_admin, login_url='/login/')
@require_http_methods(['POST'])
def create_ingredients(request):
    add_ingredient_form = AddIngredientForm(request.POST)

    if add_ingredient_form.is_valid():
        ingredient_name = add_ingredient_form.cleaned_data['name']
        add_ingredient_form.fields.pop('name')
        nutrient = add_ingredient_form.save()
        ingredient = Ingredient(name=ingredient_name, nutrient=nutrient)
        try:
            ingredient.save()

            edit_icon_html = _get_edit_icon_html()
            remove_icon_html = _get_remove_icon_html()

            return JsonResponse({
                'ingredient': ingredient.to_dict(),
                'ingredient_actions': edit_icon_html + remove_icon_html
            }, status=200)
        except IntegrityError:
            return JsonResponse({
                'errors': {'name': [u'Ingredient already exists.']}
            }, status=400)
    return JsonResponse({'errors': add_ingredient_form.errors}, status=400)

@user_passes_test(is_admin, login_url='/login/')
@require_http_methods(['DELETE'])
def delete_ingredients(request, ingredient_id):
    try:
        ingredient = Ingredient.objects.get(id=ingredient_id);
    except Ingredient.DoesNotExist:
        return JsonResponse({}, status=404)
    try:
        ingredient.delete()
    except ProtectedError:
        return JsonResponse({}, status=422)
    return JsonResponse({}, status=204)

@user_passes_test(is_admin, login_url='/login/')
@require_http_methods(['POST'])
def edit_ingredient(request, ingredient_id):
    edit_ingredient_form = AddIngredientForm(request.POST)
    try:
        ingredient = Ingredient.objects.get(id=ingredient_id);
    except Ingredient.DoesNotExist:
        return JsonResponse({}, status=404)

    if edit_ingredient_form.is_valid():
        ingredient_name = edit_ingredient_form.cleaned_data.pop('name')

        nutrient = edit_ingredient_form.save(commit=False)

        if ingredient.name != ingredient_name:
            try:
                ingredient.name = ingredient_name
                ingredient.save()
            except IntegrityError:
                return JsonResponse({
                    'errors': {'name': [u'Ingredient already exists.']}
                }, status=400)

        if nutrient != ingredient.nutrient:
            nutrient = Nutrient.objects.filter(id=ingredient.nutrient.id)
            nutrient.update(**edit_ingredient_form.cleaned_data)
            ingredient.nutrient = nutrient[0]

        edit_icon_html = _get_edit_icon_html()
        remove_icon_html = _get_remove_icon_html()

        return JsonResponse({
            'ingredient': ingredient.to_dict(),
            'ingredient_actions': edit_icon_html + remove_icon_html
        }, status=200)

    return JsonResponse({'errors': edit_ingredient_form.errors}, status=400)

app/views/recipes.py
import json

from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render
from django.http import JsonResponse

from app.builders.recipes_builders import build_recipes_table
from app.configs import ModalConfig, SelectConfig, FormConfig
from app.forms import AddRecipeForm
from app.models import Ingredient, Recipe

@login_required
@require_http_methods(["GET"])
def list_recipes(request):
    recipes_table_config = build_recipes_table()

    add_recipe_form_config = FormConfig(
        form=AddRecipeForm()
    )

    add_recipe_select_ingredient = SelectConfig(
        queryset=Ingredient.objects.all(),
        options_field='name',
        klass="select-ingredients",
        live_search_placeholder="Search ingredients",
        title="Select ingredient to add it",
        wrapper_title= "Select ingredients"
    )

    add_recipe_modal_config = ModalConfig(
        modal_id='addRecipeModal',
        modal_class='add-recipe-modal',
        content=[add_recipe_form_config, add_recipe_select_ingredient],
        title='Add recipe',
        form_class='add-recipe-form'
    )

    return render(request, 'app/recipes.html', {
        'recipes_table_config': recipes_table_config,
        'add_recipe_modal_config': add_recipe_modal_config,
    })

@login_required
@require_http_methods(["GET"])
def get_recipes_as_json(request):
    recipes = Recipe.objects.all()
    ingredients = Ingredient.objects.all()
    response = json.dumps({
        'recipes': [recipe.to_dict() for recipe in recipes],
        'ingredients': [ingredient.to_json() for ingredient in ingredients]
    })
    try:
        return JsonResponse(response, status=200, safe=False)
    except Exception as exc:
        return JsonResponse({}, status=400)

app/views/users.py
import json

from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse

from app.builders.users_builders import build_users_table
from app.configs import ModalConfig, SelectConfig, FormConfig, DetailTableConfig
from app.forms import AddRecipeForm
from app.models import User
from app.helper_functions import is_super_admin, is_admin

@login_required
@user_passes_test(is_super_admin, login_url='/login/')
@require_http_methods(["GET"])
def list_users(request):
    users_table_config = build_users_table()

    add_user_form_config = FormConfig(
        form=AddRecipeForm()
    )

    add_user_modal_config = ModalConfig(
        modal_id='addUserModal',
        modal_class='add-user-modal',
        content=[add_user_form_config],
        title='Add user',
        form_class='add-user-form'
    )

    return render(request, 'app/users/users.html', {
        'users_table_config': users_table_config,
        'add_user_modal_config': add_user_modal_config,
    })

@login_required
@require_http_methods(["GET"])
def user_details(request, user_id):
    user = get_object_or_404(User, pk=user_id)

    user_details_table_config = DetailTableConfig(
        data_dictionary=user.to_dict(),
        title="Profile info"
    )

    return render(request, 'app/users/user_details.html', {
        'user_details_table_config': user_details_table_config
    })

app/templates/app/home.html
{% extends "app/layout.html" %}

{% block head_content %}
  {{ block.super }}
  <link rel="stylesheet" href="../static/app/css/home.css">
{% endblock %}

{% block content %}
  {{ block.super }}
  {% include 'app/partials/carousel.html' %}
  <div class="animated bounceInLeft">
    <div class="container well well-lg home-main-input">
      <div class="container home-inputs col-xs-12 col-sm-9">
        <div class="home-main-text col-xs-12 col-sm-3 my-auto">
          <span>I want to eat between</span>
        </div>
        <div class="home-input col-xs-12 col-sm-3">
          <input type="text" maxlength="5" class="form-control text-center home-input-number-min">
        </div>
        <div class="home-main-text col-xs-12 col-sm-1 hyphen-sm-1">
          -
        </div>
        <div class="home-input col-xs-12 col-sm-3">
          <input type="text" maxlength="5" class="form-control text-center home-input-number-max ">
        </div>
        <div class="home-main-text col-xs-12 col-sm-1">
          calories.
        </div>
      </div>
      <div class="col-xs-12 col-sm-3">
        <button type="button" class="btn btn-warning btn-lg">
          Generate plan
          <span class="glyphicon glyphicon-chevron-right btn-glyph-after"></span>
        </button>
      </div>
    </div>
  </div>
{% endblock %}

{% block js %}
  {{ block.super}}
{% endblock %}

app/templates/app/ingredients.html
{% extends "app/layout.html" %}

{% block head_content %}
  {{ block.super }}
  <link rel="stylesheet" href="../static/app/css/common/table.css">
  <link rel="stylesheet" href="../static/app/css/common/accordion_table_xs.css">
  <link rel="stylesheet" href="../static/app/css/ingredients.css">
{% endblock %}

{% block content %}
  {{ block.super }}
  <div class="container page-header">
    <h1 class="header-title col-xs-10 col-sm-8">All ingredients <small class="header-subtitle hidden-xs hidden-sm">and their nutrients (per 100 grams)</small>
    </h1>
    <div class="header-button col-xs-2 col-sm-4">
      <button type="button" class="btn btn-success btn-md pull-right" data-toggle="modal" data-target="#addIngredientModal">
        <span class="glyphicon glyphicon-plus btn-glyph"></span>
        Add ingredient
      </button>
    </div>
  </div>
  {% include 'app/partials/table/table.html' with table_config=ingredients_table_config %}
  {% include 'app/partials/modal.html' with config=add_ingredient_modal_config %}
{% endblock %}

{% block js %}
  {{ block.super }}
  <script src="../static/app/js/common/accordion_table_xs.js"></script>
  <script src="../static/app/js/common/table.js"></script>
  <script src="../static/app/js/ingredients.js"></script>
{% endblock %}

app/templates/app/layout.html
{% load bootstrap3 %}

<!DOCTYPE>
<html>
  <head>
    {% block title %}
      <title>Idealfoods</title>
      <!-- <link rel="icon" href="../static/app/images/tab-icon.png"> -->
    {% endblock %}

    {% block head_content %}
      {% bootstrap_css %}
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
      <link rel="stylesheet" href="../static/app/css/common/common.css">
    {% endblock %}
  </head>


  <body>
    {% block nav %}
     {% include 'app/partials/navbar.html' %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block js %}
      {% bootstrap_javascript jquery=1 %}
      <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>
      <script src="../static/app/js/common/common.js"></script>
      <script src="../static/app/js/api/api.js"></script>
    {% endblock %}
  </body>

</html>

app/templates/app/login.html
{% extends "app/layout.html" %}
{% load bootstrap3 %}

{% block head_content %}
  {{ block.super }}
  <link rel="stylesheet" href="../static/app/css/login.css">
{% endblock %}

{% block content %}
  {{ block.super }}
  <div class="container page-header animated slideInLeft">
    <h1 class="header-title col-xs-12 col-sm-12 text-center">Login <small class="header-subtitle hidden-xs hidden-sm">or create an account <a href="" >here</a> .</small>
    </h1>
  </div>
  <div class="login-form-wrapper animated slideInRight" action="{% url 'app:auth_login' %}">
    <form method="post" class="login-form" action="{% url 'app:auth_login' %}">
      {% csrf_token %}
      {% bootstrap_form login_form %}
      <div class="text-center">
        <button class="btn btn-md btn-success" type="submit">
        <span class="glyphicon glyphicon-ok button-glyph"></span>Login</button>
      </div>
    </form>
  </div>

{% endblock %}

{% block js %}
  {{ block.super }}
  <script src="../static/app/js/common/common.js"></script>
{% endblock %}

app/templates/app/recipes.html
{% extends "app/layout.html" %}

{% block head_content %}
  {{ block.super }}
  <link rel="stylesheet" href="../static/app/css/common/table.css">
  <link rel="stylesheet" href="../static/app/css/common/accordion_table_xs.css">
  <link rel="stylesheet" href="../static/app/css/recipes.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
  {{ block.super }}
  <div class="container page-header">
    <h1 class="header-title col-xs-10 col-sm-8">All recipes <small class="header-subtitle hidden-xs hidden-sm">and their nutrients (per serving)</small>
    </h1>
    <div class="header-button col-xs-2 col-sm-4">
      <button type="button" class="btn btn-success btn-md pull-right" data-toggle="modal" data-target="#addRecipeModal">
        <span class="glyphicon glyphicon-plus btn-glyph"></span>
        Add recipe
      </button>
    </div>
  </div>
  {% include 'app/partials/table/table.html' with table_config=recipes_table_config %}
  {% include 'app/partials/modal.html' with config=add_recipe_modal_config %}

{% endblock %}

{% block js %}
  {{ block.super }}
  <script src="../static/app/js/common/common.js"></script>
  <script src="../static/app/js/common/accordion_table_xs.js"></script>
  <script src="../static/app/js/common/table.js"></script>
  <script src="../static/app/js/api/api.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
  <script src="../static/app/js/recipes/index.js"></script>
  <script src="../static/app/js/recipes/helpers.js"></script>
  <script src="../static/app/js/recipes/creators.js"></script>
  <script src="../static/app/js/recipes/recipes.js"></script>
{% endblock %}

app/templates/app/users.html
{% extends "app/layout.html" %}

{% block head_content %}
  {{ block.super }}
  <link rel="stylesheet" href="../static/app/css/common/table.css">
  <link rel="stylesheet" href="../static/app/css/common/accordion_table_xs.css">

{% endblock %}

{% block content %}
  {{ block.super }}
  <div class="container page-header">
    <h1 class="header-title col-xs-10 col-sm-8">All users <small class="header-subtitle hidden-xs hidden-sm">and their data</small>
    </h1>
    <div class="header-button col-xs-2 col-sm-4">
      <button type="button" class="btn btn-success btn-md pull-right" data-toggle="modal" data-target="#addRecipeModal">
        <span class="glyphicon glyphicon-plus btn-glyph"></span>
        Add user
      </button>
    </div>
  </div>
  {% include 'app/partials/table/table.html' with table_config=users_table_config %}
  {% include 'app/partials/modal.html' with config=add_user_modal_config %}

{% endblock %}

{% block js %}
  {{ block.super }}
  <script src="../static/app/js/common/common.js"></script>
  <script src="../static/app/js/common/accordion_table_xs.js"></script>
  <script src="../static/app/js/common/table.js"></script>
  <script src="../static/app/js/api/api.js"></script>
{% endblock %}